"""Add timestamp column to farmers table

Revision ID: 70260cd4c39e
Revises: c152d6b3d3f6
Create Date: 2025-04-10 13:33:02.354626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70260cd4c39e'
down_revision = 'c152d6b3d3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'timestamp')
    # ### end Alembic commands ###
