"""empty message

Revision ID: c152d6b3d3f6
Revises: ff6c240e6a66
Create Date: 2025-04-10 11:41:46.067553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c152d6b3d3f6'
down_revision = 'ff6c240e6a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drying_records', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drying_records', 'due_date')
    # ### end Alembic commands ###
