"""empty message

Revision ID: ff6c240e6a66
Revises: 
Create Date: 2025-04-10 11:09:55.219243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6c240e6a66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drying_records', sa.Column('farmer_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drying_records', 'farmer_name')
    # ### end Alembic commands ###
